In [2]:
import torch

## Initializing a Tensor ##

In [21]:
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_X = torch.tensor([[1,2,3,4],[10,9,8,7]], dtype=torch.float32,
                        device=device, requires_grad=True)

# attributes of tensor
'''
print("attributes of tensor")
print(tensor_X)
print(tensor_X.dtype)
print(tensor_X.device)
print(tensor_X.shape)
'''

## Other initialization methods
x = torch.empty(size=(3,3)) # unintialized data
x = torch.zeros((3,3))
x=torch.rand((3,3)) # uniform distribution with values between 0 and 1
x=torch.ones((3,3))
x=torch.eye(3,3) #identity matrix
x=torch.diag(torch.ones(5)) #same as identity matrix
x=torch.arange(start=0, end=5, step=1) #similar to range function in python
x=torch.linspace(start=0.1,end=1, steps=10)# will start at 0.1, end at 1 and will have 10 values between them
x=torch.empty(size=(1,5)).normal_(mean=0, std=1) # with normal distribution

## How to initialize and convert tensors to other types (int, float, double)
x=torch.arange(4) #int64 by default torch.int64
'''
print(x.bool())
print(x.short()) # convert to torch.int16
print(x.long()) # convert to int64 (Important)
print(x.half()) # convert to float16
print(x.float()) # convert to float32 (Important)
print(x.double()) # float64
'''

## Array to Tensor conversion and vice-versa
import numpy as np
x=np.zeros((2,2))
tensor_X=torch.from_numpy(x)
x=tensor_X.numpy() # convert tensor back to numpy


## Tensor Math and Comparison Operations

In [36]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

#Addition
z1=torch.empty(size=x.shape)
torch.add(x, y, out=z1)

z2 = torch.add(x, y)

z3 = x + y

y.add_(x) #store result in y (inplace operation)

# Exponentiation (Element wise operations)
z = x.pow(2)
z = x ** 2
 
# Simple comparison (Element wise operations)
z = x > 0

# Matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1, x2)
x3 = x1.mm(x2)

# Batch Matrix multiplication
batch = 32
n=10
m=20
p=30
t1 = torch.rand((batch, n, m))
t2 = torch.rand((batch, m, p))
t3 = torch.bmm(t1, t2) # (batch, n, p)

# Example of Broadcasting
x1 = torch.rand((5,5)) # matrix
x2 = torch.rand((1, 5)) # vector
 # we cannot subtract a vector from a matrix. So, when we do x1 - x2 , pytorch performs "Broadcasting"
 # Broadcasting means we expand one dimension to match the other dimension in order to perform said operation
 # in this example, (1,5) vector gets stretched out to match (5,5) with its values being copied to the bigger dim.
 # Then the subtraction is performed
z= x1 - x2
z = x1 ** x2

# Other useful tensor operations
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
z=torch.argmax(x,dim=0) # returns the index of maximum. 
z=torch.argmin(x,dim=0) # returns the index of minimum. 
z = torch.eq(x, y) # element wise comparison for a matrix
sorted_y, indices = torch.sort(x, dim=0, descending=False)

# torch.clamp is general case of relu func
z = torch.clamp(x, min=0, max=2) # clamp values 0-2 tensor([1, 2, 2]) 

x = torch.tensor([1,0,1,1,1,1], dtype=bool)
z = torch.any(x) #True
z = torch.all(x) # False


tensor([1, 2, 3]) tensor([1, 2, 2])


## Tensor Indexing

In [50]:
batch=10
features=25
x=torch.rand((batch, features))
print(x[0].shape) # get all features of 1 batch elem torch.Size([25])
print(x[:,0].shape) # get feature 0 from all batch elems torch.Size([10])

# Fancy indexing
x = torch.linspace(10, end=21, steps=11)
indices=[2,5,8]
print(x[indices])

x = torch.rand((3,5))
rows= torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols])

# More advanced indexing
x=torch.arange(10)
print(x[(x< 2) | (x>8)]) # pick out values less than 2 or greater than 8
print(x[x.remainder(2)==0])

# Use operations
print(torch.where(x > 5, x, x*2))
print(torch.tensor([0,0,1,1,1,2]).unique())
print(x.ndimension()) # will give you how many dimensions there are in the tensor
print(x.numel()) # will count how many values are in tensor

torch.Size([25])
torch.Size([10])
tensor([12.2000, 15.5000, 18.8000])
tensor([0.6658, 0.8468])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2])
1
10


## Tensor Reshaping

In [63]:
x = torch.arange(9)

x_3_3 = x.view(3,3)
x_3_3 = x.reshape(3,3)

z = x_3_3.view(-1) # flatten
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

# switch axis
z = x.permute(0, 2, 1) # torch.Size([10, 5, 2])
print(z.shape) 
# transpose is special case of permute

# adding a dimension to existing vector/matrix
print(x_3_3.unsqueeze(0).shape)
print(x_3_3.unsqueeze(-1).shape)

# remove a dimension
print(x_3_3.shape)
print(x_3_3.unsqueeze(-1).squeeze(-1).shape)

torch.Size([10, 10])
torch.Size([10, 5, 2])
torch.Size([1, 3, 3])
torch.Size([3, 3, 1])
torch.Size([3, 3])
torch.Size([3, 3])
